
import 'package:islami_task/ui/models/sura_model.dart';

abstract final class Constants
{
  static  List<String> arabicSurasNames = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];
  static List<String> englishSurasNames = [
  "Al-Fatiha",
  "Al-Baqarah",
  "Aal-E-Imran",
  "An-Nisa'",
  "Al-Ma'idah",
  "Al-An'am",
  "Al-A'raf",
  "Al-Anfal",
  "At-Tawbah",
  "Yunus",
  "Hud",
  "Yusuf",
  "Ar-Ra'd",
  "Ibrahim",
  "Al-Hijr",
  "An-Nahl",
  "Al-Isra",
  "Al-Kahf",
  "Maryam",
  "Ta-Ha",
  "Al-Anbiya",
  "Al-Hajj",
  "Al-Mu'minun",
  "An-Nur",
  "Al-Furqan",
  "Ash-Shu'ara",
  "An-Naml",
  "Al-Qasas",
  "Al-Ankabut",
  "Ar-Rum",
  "Luqman",
  "As-Sajda",
  "Al-Ahzab",
  "Saba",
  "Fatir",
  "Ya-Sin",
  "As-Saffat",
  "Sad",
  "Az-Zumar",
  "Ghafir",
  "Fussilat",
  "Ash-Shura",
  "Az-Zukhruf",
  "Ad-Dukhan",
  "Al-Jathiya",
  "Al-Ahqaf",
  "Muhammad",
  "Al-Fath",
  "Al-Hujurat",
  "Qaf",
  "Adh-Dhariyat",
  "At-Tur",
  "An-Najm",
  "Al-Qamar",
  "Ar-Rahman",
  "Al-Waqi'a",
  "Al-Hadid",
  "Al-Mujadila",
  "Al-Hashr",
  "Al-Mumtahina",
  "As-Saff",
  "Al-Jumu'a",
  "Al-Munafiqun",
  "At-Taghabun",
  "At-Talaq",
  "At-Tahrim",
  "Al-Mulk",
  "Al-Qalam",
  "Al-Haqqah",
  "Al-Ma'arij",
  "Nuh",
  "Al-Jinn",
  "Al-Muzzammil",
  "Al-Muddathir",
  "Al-Qiyamah",
  "Al-Insan",
  "Al-Mursalat",
  "An-Naba'",
  "An-Nazi'at",
  "Abasa",
  "At-Takwir",
  "Al-Infitar",
  "Al-Mutaffifin",
  "Al-Inshiqaq",
  "Al-Buruj",
  "At-Tariq",
  "Al-A'la",
  "Al-Ghashiyah",
  "Al-Fajr",
  "Al-Balad",
  "Ash-Shams",
  "Al-Lail",
  "Ad-Duha",
  "Ash-Sharh",
  "At-Tin",
  "Al-Alaq",
  "Al-Qadr",
  "Al-Bayyina",
  "Az-Zalzalah",
  "Al-Adiyat",
  "Al-Qari'a",
  "At-Takathur",
  "Al-Asr",
  "Al-Humazah",
  "Al-Fil",
  "Quraysh",
  "Al-Ma'un",
  "Al-Kawthar",
  "Al-Kafirun",
  "An-Nasr",
  "Al-Masad",
  "Al-Ikhlas",
  "Al-Falaq",
  "An-Nas"
];
  static List<String> versesNumber= [
    '7',
    '286',
    '200',
    '176',
    '120',
    '165',
    '206',
    '75',
    '129',
    '109',
    '123',
    '111',
    '43',
    '52',
    '99',
    '128',
    '111',
    '110',
    '98',
    '135',
    '112',
    '78',
    '118',
    '64',
    '77',
    '227',
    '93',
    '88',
    '69',
    '60',
    '34',
    '30',
    '73',
    '54',
    '45',
    '83',
    '182',
    '88',
    '75',
    '85',
    '54',
    '53',
    '89',
    '59',
    '37',
    '35',
    '38',
    '29',
    '18',
    '45',
    '60',
    '49',
    '62',
    '55',
    '78',
    '96',
    '29',
    '22',
    '24',
    '13',
    '14',
    '11',
    '11',
    '18',
    '12',
    '12',
    '30',
    '52',
    '52',
    '44',
    '28',
    '28',
    '20',
    '56',
    '40',
    '31',
    '50',
    '40',
    '46',
    '42',
    '29',
    '19',
    '36',
    '25',
    '22',
    '17',
    '19',
    '26',
    '30',
    '20',
    '15',
    '21',
    '11',
    '8',
    '5',
    '19',
    '5',
    '8',
    '8',
    '11',
    '11',
    '8',
    '3',
    '9',
    '5',
    '4',
    '6',
    '3',
    '6',
    '3',
    '5',
    '4',
    '5',
    '6'
  ];
  static List<Sura> suras = [
  Sura(suraNameAr: "الفاتحه", suraNameEn: "Al-Fatiha", verses: 7, fileName: "1.txt", index: 1),
  Sura(suraNameAr: "البقرة", suraNameEn: "Al-Baqarah", verses: 286, fileName: "2.txt", index: 2),
  Sura(suraNameAr: "آل عمران", suraNameEn: "Aal-E-Imran", verses: 200, fileName: "3.txt", index: 3),
  Sura(suraNameAr: "النساء", suraNameEn: "An-Nisa'", verses: 176, fileName: "4.txt", index: 4),
  Sura(suraNameAr: "المائدة", suraNameEn: "Al-Ma'idah", verses: 120, fileName: "5.txt", index: 5),
  Sura(suraNameAr: "الأنعام", suraNameEn: "Al-An'am", verses: 165, fileName: "6.txt", index: 6),
  Sura(suraNameAr: "الأعراف", suraNameEn: "Al-A'raf", verses: 206, fileName: "7.txt", index: 7),
  Sura(suraNameAr: "الأنفال", suraNameEn: "Al-Anfal", verses: 75, fileName: "8.txt", index: 8),
  Sura(suraNameAr: "التوبة", suraNameEn: "At-Tawbah", verses: 129, fileName: "9.txt", index: 9),
  Sura(suraNameAr: "يونس", suraNameEn: "Yunus", verses: 109, fileName: "10.txt", index: 10),
  Sura(suraNameAr: "هود", suraNameEn: "Hud", verses: 123, fileName: "11.txt", index: 11),
  Sura(suraNameAr: "يوسف", suraNameEn: "Yusuf", verses: 111, fileName: "12.txt", index: 12),
  Sura(suraNameAr: "الرعد", suraNameEn: "Ar-Ra'd", verses: 43, fileName: "13.txt", index: 13),
  Sura(suraNameAr: "إبراهيم", suraNameEn: "Ibrahim", verses: 52, fileName: "14.txt", index: 14),
  Sura(suraNameAr: "الحجر", suraNameEn: "Al-Hijr", verses: 99, fileName: "15.txt", index: 15),
  Sura(suraNameAr: "النحل", suraNameEn: "An-Nahl", verses: 128, fileName: "16.txt", index: 16),
  Sura(suraNameAr: "الإسراء", suraNameEn: "Al-Isra", verses: 111, fileName: "17.txt", index: 17),
  Sura(suraNameAr: "الكهف", suraNameEn: "Al-Kahf", verses: 110, fileName: "18.txt", index: 18),
  Sura(suraNameAr: "مريم", suraNameEn: "Maryam", verses: 98, fileName: "19.txt", index: 19),
  Sura(suraNameAr: "طه", suraNameEn: "Ta-Ha", verses: 135, fileName: "20.txt", index: 20),
  Sura(suraNameAr: "الأنبياء", suraNameEn: "Al-Anbiya", verses: 112, fileName: "21.txt", index: 21),
  Sura(suraNameAr: "الحج", suraNameEn: "Al-Hajj", verses: 78, fileName: "22.txt", index: 22),
  Sura(suraNameAr: "المؤمنون", suraNameEn: "Al-Mu'minun", verses: 118, fileName: "23.txt", index: 23),
  Sura(suraNameAr: "النّور", suraNameEn: "An-Nur", verses: 64, fileName: "24.txt", index: 24),
  Sura(suraNameAr: "الفرقان", suraNameEn: "Al-Furqan", verses: 77, fileName: "25.txt", index: 25),
  Sura(suraNameAr: "الشعراء", suraNameEn: "Ash-Shu'ara", verses: 227, fileName: "26.txt", index: 26),
  Sura(suraNameAr: "النّمل", suraNameEn: "An-Naml", verses: 93, fileName: "27.txt", index: 27),
  Sura(suraNameAr: "القصص", suraNameEn: "Al-Qasas", verses: 88, fileName: "28.txt", index: 28),
  Sura(suraNameAr: "العنكبوت", suraNameEn: "Al-Ankabut", verses: 69, fileName: "29.txt", index: 29),
  Sura(suraNameAr: "الرّوم", suraNameEn: "Ar-Rum", verses: 60, fileName: "30.txt", index: 30),
  Sura(suraNameAr: "لقمان", suraNameEn: "Luqman", verses: 34, fileName: "31.txt", index: 31),
  Sura(suraNameAr: "السجدة", suraNameEn: "As-Sajda", verses: 30, fileName: "32.txt", index: 32),
  Sura(suraNameAr: "الأحزاب", suraNameEn: "Al-Ahzab", verses: 73, fileName: "33.txt", index: 33),
  Sura(suraNameAr: "سبأ", suraNameEn: "Saba", verses: 54, fileName: "34.txt", index: 34),
  Sura(suraNameAr: "فاطر", suraNameEn: "Fatir", verses: 45, fileName: "35.txt", index: 35),
  Sura(suraNameAr: "يس", suraNameEn: "Ya-Sin", verses: 83, fileName: "36.txt", index: 36),
  Sura(suraNameAr: "الصافات", suraNameEn: "As-Saffat", verses: 182, fileName: "37.txt", index: 37),
  Sura(suraNameAr: "ص", suraNameEn: "Sad", verses: 88, fileName: "38.txt", index: 38),
  Sura(suraNameAr: "الزمر", suraNameEn: "Az-Zumar", verses: 75, fileName: "39.txt", index: 39),
  Sura(suraNameAr: "غافر", suraNameEn: "Ghafir", verses: 85, fileName: "40.txt", index: 40),
  Sura(suraNameAr: "فصّلت", suraNameEn: "Fussilat", verses: 54, fileName: "41.txt", index: 41),
  Sura(suraNameAr: "الشورى", suraNameEn: "Ash-Shura", verses: 53, fileName: "42.txt", index: 42),
  Sura(suraNameAr: "الزخرف", suraNameEn: "Az-Zukhruf", verses: 89, fileName: "43.txt", index: 43),
  Sura(suraNameAr: "الدّخان", suraNameEn: "Ad-Dukhan", verses: 59, fileName: "44.txt", index: 44),
  Sura(suraNameAr: "الجاثية", suraNameEn: "Al-Jathiya", verses: 37, fileName: "45.txt", index: 45),
  Sura(suraNameAr: "الأحقاف", suraNameEn: "Al-Ahqaf", verses: 35, fileName: "46.txt", index: 46),
  Sura(suraNameAr: "محمد", suraNameEn: "Muhammad", verses: 38, fileName: "47.txt", index: 47),
  Sura(suraNameAr: "الفتح", suraNameEn: "Al-Fath", verses: 29, fileName: "48.txt", index: 48),
  Sura(suraNameAr: "الحجرات", suraNameEn: "Al-Hujurat", verses: 18, fileName: "49.txt", index: 49),
  Sura(suraNameAr: "ق", suraNameEn: "Qaf", verses: 45, fileName: "50.txt", index: 50),
  Sura(suraNameAr: "الذاريات", suraNameEn: "Adh-Dhariyat", verses: 60, fileName: "51.txt", index: 51),
  Sura(suraNameAr: "الطور", suraNameEn: "At-Tur", verses: 49, fileName: "52.txt", index: 52),
  Sura(suraNameAr: "النجم", suraNameEn: "An-Najm", verses: 62, fileName: "53.txt", index: 53),
  Sura(suraNameAr: "القمر", suraNameEn: "Al-Qamar", verses: 55, fileName: "54.txt", index: 54),
  Sura(suraNameAr: "الرحمن", suraNameEn: "Ar-Rahman", verses: 78, fileName: "55.txt", index: 55),
  Sura(suraNameAr: "الواقعة", suraNameEn: "Al-Waqi'a", verses: 96, fileName: "56.txt", index: 56),
  Sura(suraNameAr: "الحديد", suraNameEn: "Al-Hadid", verses: 29, fileName: "57.txt", index: 57),
  Sura(suraNameAr: "المجادلة", suraNameEn: "Al-Mujadila", verses: 22, fileName: "58.txt", index: 58),
  Sura(suraNameAr: "الحشر", suraNameEn: "Al-Hashr", verses: 24, fileName: "59.txt", index: 59),
  Sura(suraNameAr: "الممتحنة", suraNameEn: "Al-Mumtahina", verses: 13, fileName: "60.txt", index: 60),
  Sura(suraNameAr: "الصف", suraNameEn: "As-Saff", verses: 14, fileName: "61.txt", index: 61),
  Sura(suraNameAr: "الجمعة", suraNameEn: "Al-Jumu'a", verses: 11, fileName: "62.txt", index: 62),
  Sura(suraNameAr: "المنافقون", suraNameEn: "Al-Munafiqun", verses: 11, fileName: "63.txt", index: 63),
  Sura(suraNameAr: "التغابن", suraNameEn: "At-Taghabun", verses: 18, fileName: "64.txt", index: 64),
  Sura(suraNameAr: "الطلاق", suraNameEn: "At-Talaq", verses: 12, fileName: "65.txt", index: 65),
  Sura(suraNameAr: "التحريم", suraNameEn: "At-Tahrim", verses: 12, fileName: "66.txt", index: 66),
  Sura(suraNameAr: "الملك", suraNameEn: "Al-Mulk", verses: 30, fileName: "67.txt", index: 67),
  Sura(suraNameAr: "القلم", suraNameEn: "Al-Qalam", verses: 52, fileName: "68.txt", index: 68),
  Sura(suraNameAr: "الحاقة", suraNameEn: "Al-Haqqah", verses: 52, fileName: "69.txt", index: 69),
  Sura(suraNameAr: "المعارج", suraNameEn: "Al-Ma'arij", verses: 44, fileName: "70.txt", index: 70),
  Sura(suraNameAr: "نوح", suraNameEn: "Nuh", verses: 28, fileName: "71.txt", index: 71),
  Sura(suraNameAr: "الجن", suraNameEn: "Al-Jinn", verses: 28, fileName: "72.txt", index: 72),
  Sura(suraNameAr: "المزّمّل", suraNameEn: "Al-Muzzammil", verses: 20, fileName: "73.txt", index: 73),
  Sura(suraNameAr: "المدّثر", suraNameEn: "Al-Muddathir", verses: 56, fileName: "74.txt", index: 74),
  Sura(suraNameAr: "القيامة", suraNameEn: "Al-Qiyamah", verses: 40, fileName: "75.txt", index: 75),
  Sura(suraNameAr: "الإنسان", suraNameEn: "Al-Insan", verses: 31, fileName: "76.txt", index: 76),
  Sura(suraNameAr: "المرسلات", suraNameEn: "Al-Mursalat", verses: 50, fileName: "77.txt", index: 77),
  Sura(suraNameAr: "النبأ", suraNameEn: "An-Naba'", verses: 40, fileName: "78.txt", index: 78),
  Sura(suraNameAr: "النازعات", suraNameEn: "An-Nazi'at", verses: 46, fileName: "79.txt", index: 79),
  Sura(suraNameAr: "عبس", suraNameEn: "Abasa", verses: 42, fileName: "80.txt", index: 80),
  Sura(suraNameAr: "التكوير", suraNameEn: "At-Takwir", verses: 29, fileName: "81.txt", index: 81),
  Sura(suraNameAr: "الإنفطار", suraNameEn: "Al-Infitar", verses: 19, fileName: "82.txt", index: 82),
  Sura(suraNameAr: "المطفّفين", suraNameEn: "Al-Mutaffifin", verses: 36, fileName: "83.txt", index: 83),
  Sura(suraNameAr: "الإنشقاق", suraNameEn: "Al-Inshiqaq", verses: 25, fileName: "84.txt", index: 84),
  Sura(suraNameAr: "البروج", suraNameEn: "Al-Buruj", verses: 22, fileName: "85.txt", index: 85),
  Sura(suraNameAr: "الطارق", suraNameEn: "At-Tariq", verses: 17, fileName: "86.txt", index: 86),
  Sura(suraNameAr: "الأعلى", suraNameEn: "Al-A'la", verses: 19, fileName: "87.txt", index: 87),
  Sura(suraNameAr: "الغاشية", suraNameEn: "Al-Ghashiyah", verses: 26, fileName: "88.txt", index: 88),
  Sura(suraNameAr: "الفجر", suraNameEn: "Al-Fajr", verses: 30, fileName: "89.txt", index: 89),
  Sura(suraNameAr: "البلد", suraNameEn: "Al-Balad", verses: 20, fileName: "90.txt", index: 90),
  Sura(suraNameAr: "الشمس", suraNameEn: "Ash-Shams", verses: 15, fileName: "91.txt", index: 91),
  Sura(suraNameAr: "الليل", suraNameEn: "Al-Lail", verses: 21, fileName: "92.txt", index: 92),
  Sura(suraNameAr: "الضحى", suraNameEn: "Ad-Duha", verses: 11, fileName: "93.txt", index: 93),
  Sura(suraNameAr: "الشرح", suraNameEn: "Ash-Sharh", verses: 8, fileName: "94.txt", index: 94),
  Sura(suraNameAr: "التين", suraNameEn: "At-Tin", verses: 8, fileName: "95.txt", index: 95),
  Sura(suraNameAr: "العلق", suraNameEn: "Al-Alaq", verses: 19, fileName: "96.txt", index: 96),
  Sura(suraNameAr: "القدر", suraNameEn: "Al-Qadr", verses: 5, fileName: "97.txt", index: 97),
  Sura(suraNameAr: "البينة", suraNameEn: "Al-Bayyina", verses: 8, fileName: "98.txt", index: 98),
  Sura(suraNameAr: "الزلزلة", suraNameEn: "Az-Zalzalah", verses: 8, fileName: "99.txt", index: 99),
  Sura(suraNameAr: "العاديات", suraNameEn: "Al-Adiyat", verses: 11, fileName: "100.txt", index: 100),
  Sura(suraNameAr: "القارعة", suraNameEn: "Al-Qari'a", verses: 11, fileName: "101.txt", index: 101),
  Sura(suraNameAr: "التكاثر", suraNameEn: "At-Takathur", verses: 8, fileName: "102.txt", index: 102),
  Sura(suraNameAr: "العصر", suraNameEn: "Al-Asr", verses: 3, fileName: "103.txt", index: 103),
  Sura(suraNameAr: "الهمزة", suraNameEn: "Al-Humazah", verses: 9, fileName: "104.txt", index: 104),
  Sura(suraNameAr: "الفيل", suraNameEn: "Al-Fil", verses: 5, fileName: "105.txt", index: 105),
  Sura(suraNameAr: "قريش", suraNameEn: "Quraysh", verses: 4, fileName: "106.txt", index: 106),
  Sura(suraNameAr: "الماعون", suraNameEn: "Al-Ma'un", verses: 6, fileName: "107.txt", index: 107),
  Sura(suraNameAr: "الكوثر", suraNameEn: "Al-Kawthar", verses: 3, fileName: "108.txt", index: 108),
  Sura(suraNameAr: "الكافرون", suraNameEn: "Al-Kafirun", verses: 6, fileName: "109.txt", index: 109),
  Sura(suraNameAr: "النصر", suraNameEn: "An-Nasr", verses: 3, fileName: "110.txt", index: 110),
  Sura(suraNameAr: "المسد", suraNameEn: "Al-Masad", verses: 5, fileName: "111.txt", index: 111),
  Sura(suraNameAr: "الإخلاص", suraNameEn: "Al-Ikhlas", verses: 4, fileName: "112.txt", index: 112),
  Sura(suraNameAr: "الفلق", suraNameEn: "Al-Falaq", verses: 5, fileName: "113.txt", index: 113),
  Sura(suraNameAr: "الناس", suraNameEn: "An-Nas", verses: 6, fileName: "114.txt", index: 114),
  ];

  /*
  static List<Sura> suras = [
  Sura(suraNameAr: "الفاتحه", suraNameEn: "Al-Fatiha", verses: 7, fileName: "1.txt", index: 0),
  Sura(suraNameAr: "البقرة", suraNameEn: "Al-Baqarah", verses: 286, fileName: "2.txt", index: 1),
  Sura(suraNameAr: "آل عمران", suraNameEn: "Aal-E-Imran", verses: 200, fileName: "3.txt", index: 2),
  Sura(suraNameAr: "النساء", suraNameEn: "An-Nisa'", verses: 176, fileName: "4.txt", index: 3),
  Sura(suraNameAr: "المائدة", suraNameEn: "Al-Ma'idah", verses: 120, fileName: "5.txt", index: 4),
  Sura(suraNameAr: "الأنعام", suraNameEn: "Al-An'am", verses: 165, fileName: "6.txt", index: 5),
  Sura(suraNameAr: "الأعراف", suraNameEn: "Al-A'raf", verses: 206, fileName: "7.txt", index: 6),
  Sura(suraNameAr: "الأنفال", suraNameEn: "Al-Anfal", verses: 75, fileName: "8.txt", index: 7),
  Sura(suraNameAr: "التوبة", suraNameEn: "At-Tawbah", verses: 129, fileName: "9.txt", index: 8),
  Sura(suraNameAr: "يونس", suraNameEn: "Yunus", verses: 109, fileName: "10.txt", index: 9),
  Sura(suraNameAr: "هود", suraNameEn: "Hud", verses: 123, fileName: "11.txt", index: 10),
  Sura(suraNameAr: "يوسف", suraNameEn: "Yusuf", verses: 111, fileName: "12.txt", index: 11),
  Sura(suraNameAr: "الرعد", suraNameEn: "Ar-Ra'd", verses: 43, fileName: "13.txt", index: 12),
  Sura(suraNameAr: "إبراهيم", suraNameEn: "Ibrahim", verses: 52, fileName: "14.txt", index: 13),
  Sura(suraNameAr: "الحجر", suraNameEn: "Al-Hijr", verses: 99, fileName: "15.txt", index: 14),
  Sura(suraNameAr: "النحل", suraNameEn: "An-Nahl", verses: 128, fileName: "16.txt", index: 15),
  Sura(suraNameAr: "الإسراء", suraNameEn: "Al-Isra", verses: 111, fileName: "17.txt", index: 16),
  Sura(suraNameAr: "الكهف", suraNameEn: "Al-Kahf", verses: 110, fileName: "18.txt", index: 17),
  Sura(suraNameAr: "مريم", suraNameEn: "Maryam", verses: 98, fileName: "19.txt", index: 18),
  Sura(suraNameAr: "طه", suraNameEn: "Ta-Ha", verses: 135, fileName: "20.txt", index: 19),
  Sura(suraNameAr: "الأنبياء", suraNameEn: "Al-Anbiya", verses: 112, fileName: "21.txt", index: 20),
  Sura(suraNameAr: "الحج", suraNameEn: "Al-Hajj", verses: 78, fileName: "22.txt", index: 21),
  Sura(suraNameAr: "المؤمنون", suraNameEn: "Al-Mu'minun", verses: 118, fileName: "23.txt", index: 22),
  Sura(suraNameAr: "النّور", suraNameEn: "An-Nur", verses: 64, fileName: "24.txt", index: 23),
  Sura(suraNameAr: "الفرقان", suraNameEn: "Al-Furqan", verses: 77, fileName: "25.txt", index: 24),
  Sura(suraNameAr: "الشعراء", suraNameEn: "Ash-Shu'ara", verses: 227, fileName: "26.txt", index: 25),
  Sura(suraNameAr: "النّمل", suraNameEn: "An-Naml", verses: 93, fileName: "27.txt", index: 26),
  Sura(suraNameAr: "القصص", suraNameEn: "Al-Qasas", verses: 88, fileName: "28.txt", index: 27),
  Sura(suraNameAr: "العنكبوت", suraNameEn: "Al-Ankabut", verses: 69, fileName: "29.txt", index: 28),
  Sura(suraNameAr: "الرّوم", suraNameEn: "Ar-Rum", verses: 60, fileName: "30.txt", index: 29),
  Sura(suraNameAr: "لقمان", suraNameEn: "Luqman", verses: 34, fileName: "31.txt", index: 30),
  Sura(suraNameAr: "السجدة", suraNameEn: "As-Sajda", verses: 30, fileName: "32.txt", index: 31),
  Sura(suraNameAr: "الأحزاب", suraNameEn: "Al-Ahzab", verses: 73, fileName: "33.txt", index: 32),
  Sura(suraNameAr: "سبأ", suraNameEn: "Saba", verses: 54, fileName: "34.txt", index: 33),
  Sura(suraNameAr: "فاطر", suraNameEn: "Fatir", verses: 45, fileName: "35.txt", index: 34),
  Sura(suraNameAr: "يس", suraNameEn: "Ya-Sin", verses: 83, fileName: "36.txt", index: 35),
  Sura(suraNameAr: "الصافات", suraNameEn: "As-Saffat", verses: 182, fileName: "37.txt", index: 36),
  Sura(suraNameAr: "ص", suraNameEn: "Sad", verses: 88, fileName: "38.txt", index: 37),
  Sura(suraNameAr: "الزمر", suraNameEn: "Az-Zumar", verses: 75, fileName: "39.txt", index: 38),
  Sura(suraNameAr: "غافر", suraNameEn: "Ghafir", verses: 85, fileName: "40.txt", index: 39),
  Sura(suraNameAr: "فصّلت", suraNameEn: "Fussilat", verses: 54, fileName: "41.txt", index: 40),
  Sura(suraNameAr: "الشورى", suraNameEn: "Ash-Shura", verses: 53, fileName: "42.txt", index: 41),
  Sura(suraNameAr: "الزخرف", suraNameEn: "Az-Zukhruf", verses: 89, fileName: "43.txt", index: 42),
  Sura(suraNameAr: "الدّخان", suraNameEn: "Ad-Dukhan", verses: 59, fileName: "44.txt", index: 43),
  Sura(suraNameAr: "الجاثية", suraNameEn: "Al-Jathiya", verses: 37, fileName: "45.txt", index: 44),
  Sura(suraNameAr: "الأحقاف", suraNameEn: "Al-Ahqaf", verses: 35, fileName: "46.txt", index: 45),
  Sura(suraNameAr: "محمد", suraNameEn: "Muhammad", verses: 38, fileName: "47.txt", index: 46),
  Sura(suraNameAr: "الفتح", suraNameEn: "Al-Fath", verses: 29, fileName: "48.txt", index: 47),
  Sura(suraNameAr: "الحجرات", suraNameEn: "Al-Hujurat", verses: 18, fileName: "49.txt", index: 48),
  Sura(suraNameAr: "ق", suraNameEn: "Qaf", verses: 45, fileName: "50.txt", index: 49),
  Sura(suraNameAr: "الذاريات", suraNameEn: "Adh-Dhariyat", verses: 60, fileName: "51.txt", index: 50),
  Sura(suraNameAr: "الطور", suraNameEn: "At-Tur", verses: 49, fileName: "52.txt", index: 51),
  Sura(suraNameAr: "النجم", suraNameEn: "An-Najm", verses: 62, fileName: "53.txt", index: 52),
  Sura(suraNameAr: "القمر", suraNameEn: "Al-Qamar", verses: 55, fileName: "54.txt", index: 53),
  Sura(suraNameAr: "الرحمن", suraNameEn: "Ar-Rahman", verses: 78, fileName: "55.txt", index: 54),
  Sura(suraNameAr: "الواقعة", suraNameEn: "Al-Waqi'a", verses: 96, fileName: "56.txt", index: 55),
  Sura(suraNameAr: "الحديد", suraNameEn: "Al-Hadid", verses: 29, fileName: "57.txt", index: 56),
  Sura(suraNameAr: "المجادلة", suraNameEn: "Al-Mujadila", verses: 22, fileName: "58.txt", index: 57),
  Sura(suraNameAr: "الحشر", suraNameEn: "Al-Hashr", verses: 24, fileName: "59.txt", index: 58),
  Sura(suraNameAr: "الممتحنة", suraNameEn: "Al-Mumtahina", verses: 13, fileName: "60.txt", index: 59),
  Sura(suraNameAr: "الصف", suraNameEn: "As-Saff", verses: 14, fileName: "61.txt", index: 60),
  Sura(suraNameAr: "الجمعة", suraNameEn: "Al-Jumu'a", verses: 11, fileName: "62.txt", index: 61),
  Sura(suraNameAr: "المنافقون", suraNameEn: "Al-Munafiqun", verses: 11, fileName: "63.txt", index: 62),
  Sura(suraNameAr: "التغابن", suraNameEn: "At-Taghabun", verses: 18, fileName: "64.txt", index: 63),
  Sura(suraNameAr: "الطلاق", suraNameEn: "At-Talaq", verses: 12, fileName: "65.txt", index: 64),
  Sura(suraNameAr: "التحريم", suraNameEn: "At-Tahrim", verses: 12, fileName: "66.txt", index: 65),
  Sura(suraNameAr: "الملك", suraNameEn: "Al-Mulk", verses: 30, fileName: "67.txt", index: 66),
  Sura(suraNameAr: "القلم", suraNameEn: "Al-Qalam", verses: 52, fileName: "68.txt", index: 67),
  Sura(suraNameAr: "الحاقة", suraNameEn: "Al-Haqqah", verses: 52, fileName: "69.txt", index: 68),
  Sura(suraNameAr: "المعارج", suraNameEn: "Al-Ma'arij", verses: 44, fileName: "70.txt", index: 69),
  Sura(suraNameAr: "نوح", suraNameEn: "Nuh", verses: 28, fileName: "71.txt", index: 70),
  Sura(suraNameAr: "الجن", suraNameEn: "Al-Jinn", verses: 28, fileName: "72.txt", index: 71),
  Sura(suraNameAr: "المزّمّل", suraNameEn: "Al-Muzzammil", verses: 20, fileName: "73.txt", index: 72),
  Sura(suraNameAr: "المدّثر", suraNameEn: "Al-Muddathir", verses: 56, fileName: "74.txt", index: 73),
  Sura(suraNameAr: "القيامة", suraNameEn: "Al-Qiyamah", verses: 40, fileName: "75.txt", index: 74),
  Sura(suraNameAr: "الإنسان", suraNameEn: "Al-Insan", verses: 31, fileName: "76.txt", index: 75),
  Sura(suraNameAr: "المرسلات", suraNameEn: "Al-Mursalat", verses: 50, fileName: "77.txt", index: 76),
  Sura(suraNameAr: "النبأ", suraNameEn: "An-Naba'", verses: 40, fileName: "78.txt", index: 77),
  Sura(suraNameAr: "النازعات", suraNameEn: "An-Nazi'at", verses: 46, fileName: "79.txt", index: 78),
  Sura(suraNameAr: "عبس", suraNameEn: "Abasa", verses: 42, fileName: "80.txt", index: 79),
  Sura(suraNameAr: "التكوير", suraNameEn: "At-Takwir", verses: 29, fileName: "81.txt", index: 80),
  Sura(suraNameAr: "الإنفطار", suraNameEn: "Al-Infitar", verses: 19, fileName: "82.txt", index: 81),
  Sura(suraNameAr: "المطفّفين", suraNameEn: "Al-Mutaffifin", verses: 36, fileName: "83.txt", index: 82),
  Sura(suraNameAr: "الإنشقاق", suraNameEn: "Al-Inshiqaq", verses: 25, fileName: "84.txt", index: 83),
  Sura(suraNameAr: "البروج", suraNameEn: "Al-Buruj", verses: 22, fileName: "85.txt", index: 84),
  Sura(suraNameAr: "الطارق", suraNameEn: "At-Tariq", verses: 17, fileName: "86.txt", index: 85),
  Sura(suraNameAr: "الأعلى", suraNameEn: "Al-A'la", verses: 19, fileName: "87.txt", index: 86),
  Sura(suraNameAr: "الغاشية", suraNameEn: "Al-Ghashiyah", verses: 26, fileName: "88.txt", index: 87),
  Sura(suraNameAr: "الفجر", suraNameEn: "Al-Fajr", verses: 30, fileName: "89.txt", index: 88),
  Sura(suraNameAr: "البلد", suraNameEn: "Al-Balad", verses: 20, fileName: "90.txt", index: 89),
  Sura(suraNameAr: "الشمس", suraNameEn: "Ash-Shams", verses: 15, fileName: "91.txt", index: 90),
  Sura(suraNameAr: "الليل", suraNameEn: "Al-Lail", verses: 21, fileName: "92.txt", index: 91),
  Sura(suraNameAr: "الضحى", suraNameEn: "Ad-Duha", verses: 11, fileName: "93.txt", index: 92),
  Sura(suraNameAr: "الشرح", suraNameEn: "Ash-Sharh", verses: 8, fileName: "94.txt", index: 93),
  Sura(suraNameAr: "التين", suraNameEn: "At-Tin", verses: 8, fileName: "95.txt", index: 94),
  Sura(suraNameAr: "العلق", suraNameEn: "Al-Alaq", verses: 19, fileName: "96.txt", index: 95),
  Sura(suraNameAr: "القدر", suraNameEn: "Al-Qadr", verses: 5, fileName: "97.txt", index: 96),
  Sura(suraNameAr: "البينة", suraNameEn: "Al-Bayyina", verses: 8, fileName: "98.txt", index: 97),
  Sura(suraNameAr: "الزلزلة", suraNameEn: "Az-Zalzalah", verses: 8, fileName: "99.txt", index: 98),
  Sura(suraNameAr: "العاديات", suraNameEn: "Al-Adiyat", verses: 11, fileName: "100.txt", index: 99),
  Sura(suraNameAr: "القارعة", suraNameEn: "Al-Qari'a", verses: 11, fileName: "101.txt", index: 100),
  Sura(suraNameAr: "التكاثر", suraNameEn: "At-Takathur", verses: 8, fileName: "102.txt", index: 101),
  Sura(suraNameAr: "العصر", suraNameEn: "Al-Asr", verses: 3, fileName: "103.txt", index: 102),
  Sura(suraNameAr: "الهمزة", suraNameEn: "Al-Humazah", verses: 9, fileName: "104.txt", index: 103),
  Sura(suraNameAr: "الفيل", suraNameEn: "Al-Fil", verses: 5, fileName: "105.txt", index: 104),
  Sura(suraNameAr: "قريش", suraNameEn: "Quraysh", verses: 4, fileName: "106.txt", index: 105),
  Sura(suraNameAr: "الماعون", suraNameEn: "Al-Ma'un", verses: 6, fileName: "107.txt", index: 106),
  Sura(suraNameAr: "الكوثر", suraNameEn: "Al-Kawthar", verses: 3, fileName: "108.txt", index: 107),
  Sura(suraNameAr: "الكافرون", suraNameEn: "Al-Kafirun", verses: 6, fileName: "109.txt", index: 108),
  Sura(suraNameAr: "النصر", suraNameEn: "An-Nasr", verses: 3, fileName: "110.txt", index: 109),
  Sura(suraNameAr: "المسد", suraNameEn: "Al-Masad", verses: 5, fileName: "111.txt", index: 110),
  Sura(suraNameAr: "الإخلاص", suraNameEn: "Al-Ikhlas", verses: 4, fileName: "112.txt", index: 111),
  Sura(suraNameAr: "الفلق", suraNameEn: "Al-Falaq", verses: 5, fileName: "113.txt", index: 112),
  Sura(suraNameAr: "الناس", suraNameEn: "An-Nas", verses: 6, fileName: "114.txt", index: 113),
  ];
  */


}
